Repository LForchini/Multiverse-Web-Store, pull requests merged in 2022-01, with the labels that each got.

#3 Added basic wireframes
  first-draft.drawio
Labels: documentation

#8 Added UML Diagrams
  docs/cart-info-sequence.png
  docs/cart-info-sequence.puml
  docs/classes.png
  docs/classes.puml
  docs/product-info-sequence.png
  docs/product-info-sequence.puml
  docs/use-cases.png
  docs/use-cases.puml
Labels: documentation

#13 Added Figma Prototype
  docs/Shop Project Figma Prototype 1.png
Labels: documentation

#14 Enhancement 9
  server/index.ts
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: enhancement

#15 Dev
  client/Procfile
  docs/Shop Project Figma Prototype 1.png
  docs/cart-info-sequence.png
  docs/cart-info-sequence.puml
  docs/classes.png
  docs/classes.puml
  docs/first-draft.drawio
  docs/product-info-sequence.png
  docs/product-info-sequence.puml
  docs/use-cases.png
  docs/use-cases.puml
  server/Procfile
  server/index.ts
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: enhancement

#17 Added deploy scripts
  deploy_client.sh
  deploy_server.sh
  server/package.json
Labels: enhancement

#20 Create basic endpoints
  .gitignore
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/models/cart.model.ts
  server/src/models/category.model.ts
  server/src/models/product.model.ts
  server/src/models/row.model.ts
  server/src/routes/cart-route.ts
  server/src/routes/product-route.ts
  server/src/sequelize.ts
  server/tests/models/cart.test.ts
  server/tsconfig.json
Labels: enhancement

#22 Seed values are loaded in
  server/index.ts
  server/src/seed.json
  server/src/sequelize.ts
Labels: enhancement

#28 Integrated front and back-end
  .gitignore
  client/package-lock.json
  client/package.json
  client/server.js
  client/views/cart.hbs
  client/views/item.hbs
  client/views/layouts/index.hbs
  client/views/main.hbs
  client/views/partials/footer.hbs
  server/index.ts
  server/src/models/product.model.ts
Labels: enhancement

#38 Added graphical wireframes
  docs/first-draft-Cart.drawio.png
  docs/first-draft-Item Information.drawio.png
  docs/first-draft-User not logged in.drawio.png
Labels: documentation

#40 Added additional endpoints
  client/package-lock.json
  client/package.json
  client/server.js
  server/src/routes/cart-route.ts
Labels: enhancement

#43 Added basic server-side validation
  server/package-lock.json
  server/package.json
  server/src/models/row.model.ts
  server/src/routes/cart-route.ts
Labels: enhancement

#47 Added some tests
  server/src/models/row.model.ts
  server/tests/index.test.ts
  server/tests/models/cart.test.ts
  server/tests/models/product.test.ts
  server/tests/models/row.test.ts
  server/tests/sequelize.test.ts
Labels: documentation, enhancement

#42 Enhancement 29
  client/public/cart.css
  client/public/cart.js
  client/views/cart.hbs
  client/views/item.hbs
  client/views/main.hbs
Labels: enhancement

#48 Integrated front and backend
  client/public/cart.js
  client/server.js
  client/views/item.hbs
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/routes/cart-route.ts
Labels: enhancement

#54 Does not show acceptance page
  client/views/item.hbs
  server/index.ts
Labels: bug, enhancement

#57 Main merge
  .github/workflows/ci.yml
  .gitignore
  README.md
  client/Procfile
  client/package-lock.json
  client/package.json
  client/public/cart.css
  client/public/cart.js
  client/public/index.js
  client/public/item.css
  client/public/logo1.png
  client/public/style.css
  client/server.js
  client/views/cart.hbs
  client/views/item.hbs
  client/views/layouts/index.hbs
  client/views/main.hbs
  client/views/partials/footer.hbs
  deploy_client.sh
  deploy_server.sh
  docs/first-draft-Cart.drawio.png
  docs/first-draft-Item Information.drawio.png
  docs/first-draft-User not logged in.drawio.png
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/models/cart.model.ts
  server/src/models/category.model.ts
  server/src/models/product.model.ts
  server/src/models/row.model.ts
  server/src/routes/cart-route.ts
  server/src/routes/product-route.ts
  server/src/seed.json
  server/src/sequelize.ts
  server/tests/models/cart.test.ts
  server/tests/models/product.test.ts
  server/tests/models/row.test.ts
  server/tests/sequelize.test.ts
  server/tsconfig.json
Labels: documentation, enhancement

#62 Added image
  docs/Database Design.png
Labels: documentation

#75 Created folders for the sprints
  docs/Sprint 1 NVP/Database Design.png
  docs/Sprint 1 NVP/Shop Project Figma Prototype 1.png
  docs/Sprint 1 NVP/cart-info-sequence.png
  docs/Sprint 1 NVP/cart-info-sequence.puml
  docs/Sprint 1 NVP/classes.png
  docs/Sprint 1 NVP/classes.puml
  docs/Sprint 1 NVP/first-draft-Cart.drawio.png
  docs/Sprint 1 NVP/first-draft-Item Information.drawio.png
  docs/Sprint 1 NVP/first-draft-User not logged in.drawio.png
  docs/Sprint 1 NVP/first-draft.drawio
  docs/Sprint 1 NVP/product-info-sequence.png
  docs/Sprint 1 NVP/product-info-sequence.puml
  docs/Sprint 1 NVP/use-cases.png
  docs/Sprint 1 NVP/use-cases.puml
  docs/Sprint 2/classes 2nd cycle.png
Labels: documentation

#79 Added login and logout sequence diagrams
  docs/Sprint 2/classes 2nd cycle.puml
  docs/Sprint 2/login-sequence.png
  docs/Sprint 2/login-sequence.puml
  docs/Sprint 2/logout-sequence.png
  docs/Sprint 2/logout-sequence.puml
Labels: documentation
